name: complex-workflow

on:
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  windows:
    runs-on: windows-latest
    steps:
      - name: print date
        run: date
  macos:
    runs-on: macos-latest
    steps:
      - name: print date
        run: date
  finaljob:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: print date
        run: date
