name: "Test secrets"
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  echoSecrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets val
        run: |
          echo "accessing secrets, My name is ${{ secrets.MY_NAME }}"
          echo "and i work for ${{ secrets.MY_ORG }}."
          echo "To add secrets go to Repository settings -> secrets -> add new secret and it can be used `with` keyword in steps to pass as argument."